name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        # Repository name with owner. For example, actions/checkout
        # Default: ${{ github.repository }}
        repository: '/emscripten-core/emsdk'
    - name: fulfil
      run: sudo apt-get install g++-11 && cd emsdk && ./emsdk install latest && ./emsdk activate latest
    - name: configure
      run: source emsdk/emsdk_env.sh && aclocal && automake --add-missing && autoreconf && ./configure CXX=em++
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck DISTCHECK_CONFIGURE_FLAGS='CXX=g++-11'
