name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: autoscan && ln -T configure.scan configure.ac && autoconf && ./configure
    - name: make || cat configure.scan
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
